import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import Navigator from "@/components/navigator";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Business Stanely",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen flex overflow-hidden`}>
        <SidebarProvider>
          <AppSidebar /> {/* This will take fixed width (e.g., 250px) */}
          <main className="flex flex-col flex-1 overflow-hidden">
            <SidebarTrigger />
            <Navigator />
            <div className="flex-1 overflow-auto">
              {children}
            </div>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}

