import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import '@/lib/cronInit'; // Initialize cron scheduler


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LegalStanley",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen flex overflow-hidden`}>
        {children}
        <ToastContainer
          position="top-right"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop
          closeOnClick
          rtl={false}
          draggable
          theme="light"
          pauseOnHover={false}
          pauseOnFocusLoss={false}
          limit={3}
          containerId="main-toast-container"
          stacked={false}
        />
      </body>
    </html>
  );
}
